#!/bin/sh

PATH='/usr/bin:/usr/sbin:/bin:/sbin'

api=$1
key=$2
chat_id=$3

while [ true ]
do
	curl -k -X POST $api$key/sendChatAction -d "chat_id=$chat_id" -d "action=typing" &> /tmp/telegram.log   
	echo "Typing"
	sleep 6
done
