#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2019 OpenWrt.org

START=95
STOP=15

USE_PROCD=1
PROG=/sbin/telegram_bot
NAME=tbot

start_service () {
        echo "Starting Service..."
        config_load "${NAME}"
        procd_open_instance
        procd_set_param command "$PROG"
        procd_set_param respawn
        echo "tbot started!"
}

stop_service() {
        kill $(pgrep -f telegram_bot)
}

restart(){      
        stop_service    
        sleep 1 
        start_service   
}               
