#!/bin/sh

source /lib/functions/network.sh
network_flush_cache
network_find_wan NET_IF
network_find_wan6 NET_IF6
network_get_ipaddr NET_ADDR "${NET_IF}"
network_get_ipaddr6 NET_ADDR6 "${NET_IF6}"
if [ ! -z $NET_ADDR ]; then
        echo "IPv4: ${NET_ADDR}"
else
        echo "IPv4 not set"
fi
if [ ! -z $NET_ADDR6 ]; then
        echo "IPv6: ${NET_ADDR6}"
else
        echo "IPv6 not set"
fi
